version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: unless-stopped
    environment:
      - DOMAIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app.conf:/etc/nginx/templates/default.conf.template
      - ./data/letsencrypt:/etc/letsencrypt:ro
      - ./data/certbot:/var/www/certbot
      - ./data/logs:/var/log/nginx
  certbot:
    container_name: certbot
    image: certbot/certbot:v2.0.0
    depends_on:
      - nginx
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'


networks:
  default:
    name: trufi-server